### ISSUE TITLE
No Activity found to handle Intent { act=android.content.pm.action.CONFIRM_PERMISSIONS flg=0x10000000 pkg=com.android.packageinstaller (has extras) }

### ISSUE THREAD

**Issue by katjarutnik** [nkalra0123/splitapkinstall#5]
Exception happens when you try to install split apks - install service is unable to show confirmation dialog.

Affected devices:

Samsung Note 3 (Android 5),
SM-G850F (Android 5.0.2),
SM-950F (Android 5.0.2),
SM-N9005 (Android 5),
Galaxy S5 (Android 5),
Galaxy S4 (Android 5.0.1).

2022-01-19 10:39:29.607 8520-8520/org.faith.apkinstaller D/APKInstallService: Requesting user confirmation for installation
2022-01-19 10:39:29.632 8520-8520/org.faith.apkinstaller E/APKInstallService: PackageInstaller.STATUS_PENDING_USER_ACTION exception
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.content.pm.action.CONFIRM_PERMISSIONS flg=0x10000000 pkg=com.android.packageinstaller (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1499)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1616)
        at android.app.ContextImpl.startActivity(ContextImpl.java:1598)
        at android.content.ContextWrapper.startActivity(ContextWrapper.java:337)
        at com.faith.apkinstaller.APKInstallService.onStartCommand(APKInstallService.java:23)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3422)
        at android.app.ActivityThread.access$2200(ActivityThread.java:181)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6117)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by nkalra0123** [comment]
I tried on a Android 5.0.2 Emulator from Android studio, And the app is working fine.
D/APKInstallService( 2809): Requesting user confirmation for installation
**I/ActivityManager( 1531): START u0 {act=android.content.pm.action.CONFIRM_PERMISSIONS flg=0x10000000 pkg=com.android.packageinstaller cmp=com.android.packageinstaller/.PackageInstallerActivity (has extras)} from uid 10054 on display 0**
At this time I get this screen (Activity)
![image](https://user-images.githubusercontent.com/4373248/150176506-5db4ecb8-0b59-4a70-a100-e80942e247da.png)

I don't have any of these Samsung devices for testing. So unable to debug more about this issue.
